export async function GET(
  req: Request
) {
  try {
    
  } catch (error) {
    console.log("[ERR_FETCH_USERS]", error);
    throw new Error("Internal server error")
  }
}